### ISSUE TITLE
Variable parsing bugs

### ISSUE THREAD

**Issue by louisfd** [tracel-ai/cubecl#11]
There are a few bugs in the parsing of CubeCL, which I found while writing the matmul, but they all have easy workarounds. 

- [ ] When using a variable inside a closure or a for loop it cannot be reused later on. E.g.: 
```rust
let x = Comptime::map(config, |c| c.x);
let c = UInt::new(0); // bugs
```
or
```rust
    let mut a = F::vectorized_empty(Comptime::get(out_vec));
    for i in range(0u32, 4u32, Comptime::new(true)) {
        a[i] = accumulator_sm[read_pos_0_with_n_iter + i];
    }
    out[out_write_pos_0_with_n_iter / out_vec_r] = a;

    let mut a = F::vectorized_empty(Comptime::get(out_vec));
    for i in range(0u32, 4u32, Comptime::new(true)) {
        a[i] = accumulator_sm[read_pos_0_with_n_iter + i];
    }
    out[out_write_pos_0_with_n_iter / out_vec_r] = a;
```

Plus, the error message in this case is "Cannot subtract with overflow" which is very misleading. 

- [ ] It's impossible to have runtime variables coming from Comptime interacting with each other: 
```rust
    let x = Comptime::runtime(...); 
    let y = Comptime::runtime(...); 
    let z = x * y;  // bugs
```

**Comment by TomWyllie** [comment]
\+ Another one I think. The following gives the error `proc-macro panicked: not yet implemented: Codegen: unsupported op UnOp::Neg(Minus)`, presumably this will be implemented down the line.

```
#[cube]
fn negative<F: Float>(x: F) -> F {
    -x
}
```
If you try and create a float by passing in a negative `f32` to `F::new()` it is still detected as a negative unary operation, so the following also doesn't compile. I would've thought it's a bug to parse that as a unary op.

```
#[cube]
fn negative<F: Float>(x: F) -> F {
    F::new(-1.0) * x
}
```

But you can trick the compiler into treating is as a subtract operation by doing the following which works as expected :frog:

```
#[cube]
fn negative<F: Float>(x: F) -> F {
    F::new(0.0 - 1.0) * x
}
```

**Comment by louisfd** [comment]
> + Another one I think. The following gives the error `proc-macro panicked: not yet implemented: Codegen: unsupported op UnOp::Neg(Minus)`, presumably this will be implemented down the line.

Indeed, Rust parses -1. not as a literal but as the unary op Neg over the literal 1. The only UnOp implemented is Not (not to be confounded with Neg), so yeah it really never was implemented 😅 it should be easy by following the same pattern as Not
