### ISSUE TITLE
CUDA kernels names shouldn't all be "kernel"

### ISSUE THREAD

**Issue by torsteingrindvik** [tracel-ai/cubecl#234]
Hardcoded here:

1. https://github.com/tracel-ai/cubecl/blob/main/crates/cubecl-cuda/src/compute/server.rs#L366
2. https://github.com/tracel-ai/cubecl/blob/main/crates/cubecl-cpp/src/shared/kernel.rs#L125

I think that perhaps either
1. The kernel name should always be equal to the Rust name, or
2. It should default to the Rust name but let the user name it via some API or via the proc macro (e.g. `#[cube(launch, name = "foo")]`

The reason for having names is that if profiling with Nsight tools we can see which kernels are which. This is diffifcult when the names are the same.

**Comment by nathanielsimard** [comment]
I don't think we need the name to be passed as attribute, but we could. Otherwise we can take the function name for the kernel name.

```rust
#[cube(launch)]  // The name will be `my_algo` instead of `kernel`
fn my_algo() {
   ...
}
```
