### ISSUE TITLE
v0.1.1 release does not contain the CubeDim change

### ISSUE THREAD

**Issue by shinglyu** [tracel-ai/cubecl#44]
In your v0.1.1 tag, the code https://github.com/tracel-ai/cubecl/blame/2b95a9e245bf4362b497866ee24bec399d1c74fb/crates/cubecl-core/src/lib.rs#L57 seems to be based on an older version from 3 weeks ago. The function `calculate_cube_count_elemwise`

```rust
pub fn calculate_cube_count_elemwise<S: ComputeServer>(
    num_elems: usize,
    cube_dim: usize,
) -> CubeCount<S> {
``` 
seems to be revered to use`cube_dim: usize` instead of `cube_dim: CubeDim`.

The `CubeDim` change was pushed 5 days ago in https://github.com/tracel-ai/cubecl/commit/367bd4c38ae16bb4660a60399bbb4a4c95e02755. But it was (accidentally?) reverted in 6eaccca2962c041b8edc857f9a57dca128f59265.

This breaks Burn's example: https://github.com/tracel-ai/burn/issues/2082. Could you kindly bring back the `CubeDim` change the release a new version? Or should Burn be revered to use `usize`?

**Comment by nathanielsimard** [comment]
Close https://github.com/tracel-ai/burn/issues/2082#issuecomment-2262979359
